[workspace]
authors = ["dmartins <dmartins@smart-robotics.nl>"]
channels = ["https://prefix.dev/robostack-jazzy", "conda-forge"]
name = "distrimuse-ros2-api"
platforms = ["linux-64"]
preview = ["pixi-build"]
version = "0.1.0"

[dependencies]
python = ">=3.11"
pytest = ">=8"
ros-jazzy-distrimuse-ros2-api = { path = "." }

[tasks]
test = "pytest tests/"

[package.build.backend]
channels = ["https://prefix.dev/conda-forge"]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"
